"""empty message

Revision ID: f8b9601483c7
Revises: 7023a4837142
Create Date: 2017-03-03 16:37:47.091356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b9601483c7'
down_revision = '7023a4837142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('office', sa.Column('phone', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('office', 'phone')
    # ### end Alembic commands ###
